#!/usr/bin/env bash
# NanoBK Proxy Suite — Wrangler nanob Bundle Test
#
# Tests that the nanob Worker can be bundled by Wrangler without errors.
# Does NOT deploy to Cloudflare or require authentication.
#
# Usage:
#   bash tests/wrangler-nanob-dry-run.sh

set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKER_DIR="${ROOT}/workers/nanob"
TOML_PATH="${WORKER_DIR}/wrangler.toml"
OUT_DIR="${TMPDIR:-/tmp}/nanob-dry-run"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

pass() { echo -e "  ${GREEN}✓${NC} $*"; }
fail() { echo -e "  ${RED}✗${NC} $*" >&2; }
warn() { echo -e "  ${YELLOW}!${NC} $*"; }

HAD_EXISTING_TOML=0
CLEANED_UP=0

cleanup() {
  if [[ "$CLEANED_UP" == "1" ]]; then
    return
  fi
  CLEANED_UP=1

  if [[ "$HAD_EXISTING_TOML" == "0" ]] && [[ -f "$TOML_PATH" ]]; then
    rm -f "$TOML_PATH"
  fi

  rm -rf "$OUT_DIR"
}

trap cleanup EXIT

echo ""
echo "=== Wrangler nanob Bundle Test ==="
echo ""

# ── Check prerequisites ─────────────────────────────────────────────────────

if ! command -v node &>/dev/null; then
  fail "node not found. Install Node.js first."
  exit 1
fi
pass "node: $(node --version)"

WRANGLER=""
if command -v npx &>/dev/null; then
  WRANGLER="npx wrangler"
elif command -v wrangler &>/dev/null; then
  WRANGLER="wrangler"
else
  fail "wrangler not found. Install with: npm install -g wrangler"
  exit 1
fi
pass "wrangler detected"

# ── Generate test wrangler.toml ─────────────────────────────────────────────

echo ""
echo "--- Generating test wrangler.toml ---"
echo ""

if [[ -f "$TOML_PATH" ]]; then
  HAD_EXISTING_TOML=1
  warn "Existing wrangler.toml found, will restore after test"
fi

cat > "$TOML_PATH" <<'EOF'
# Test wrangler.toml — generated by tests/wrangler-nanob-dry-run.sh
name = "nanob-test"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "NANOB_GEO_CACHE"
id = "00000000000000000000000000000000"

[vars]
NANOK_ORIGIN = "https://nanok.example.workers.dev"
NANOK_SUB_PATH = "/jb"
NANOB_PATH = "/jb"
EDGE_HOST = ""
EDGE_SUB_PATH = "/sub?target=clash"
EOF

pass "Generated test wrangler.toml"

# ── Run wrangler deploy --dry-run ───────────────────────────────────────────

echo ""
echo "--- Running wrangler deploy --dry-run ---"
echo ""

rm -rf "$OUT_DIR"

if (
  cd "$WORKER_DIR"
  $WRANGLER deploy --dry-run --outdir "$OUT_DIR" --config wrangler.toml 2>&1
); then
  pass "wrangler deploy --dry-run succeeded"
else
  fail "wrangler deploy --dry-run failed"
  exit 1
fi

# ── Check output ────────────────────────────────────────────────────────────

echo ""
echo "--- Checking bundle output ---"
echo ""

if [[ -d "$OUT_DIR" ]]; then
  local_count=$(find "$OUT_DIR" -type f | wc -l | tr -d ' ')
  pass "Output directory: ${OUT_DIR} (${local_count} files)"

  if [[ -f "$OUT_DIR/index.js" ]]; then
    pass "Bundle output contains index.js"
    local_size=$(wc -c < "$OUT_DIR/index.js" | tr -d ' ')
    pass "Bundle size: ${local_size} bytes"
  else
    if find "$OUT_DIR" -name '*.js' -type f | head -1 | grep -q .; then
      pass "Bundle output contains JS file(s)"
    else
      fail "No JS output found in ${OUT_DIR}"
      exit 1
    fi
  fi
else
  fail "Output directory not found: ${OUT_DIR}"
  exit 1
fi

# ── Verify no git changes ───────────────────────────────────────────────────

echo ""
echo "--- Verifying no git changes ---"
echo ""

if [[ "$HAD_EXISTING_TOML" == "0" ]]; then
  rm -f "$TOML_PATH"
fi
CLEANED_UP=1

if git -C "$ROOT" diff --quiet 2>/dev/null && git -C "$ROOT" diff --cached --quiet 2>/dev/null; then
  pass "No uncommitted git changes"
else
  warn "Git has uncommitted changes (may be pre-existing)"
fi

echo ""
echo -e "  ${GREEN}Bundle test passed!${NC}"
echo ""
