#!/usr/bin/env bash
# NanoBK Proxy Suite — Wrangler nanok Bundle Test
#
# Tests that the nanok Worker can be bundled by Wrangler without errors.
# Does NOT deploy to Cloudflare or require authentication.
#
# If workers/nanok/wrangler.toml already exists, it is backed up and restored.
#
# Usage:
#   bash tests/wrangler-nanok-dry-run.sh

set -Eeuo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORKER_DIR="${ROOT}/workers/nanok"
TOML_PATH="${WORKER_DIR}/wrangler.toml"
OUT_DIR="${TMPDIR:-/tmp}/nanok-dry-run"
BACKUP_TOML="${TMPDIR:-/tmp}/nanok-wrangler.toml.backup.$$"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

pass() { echo -e "  ${GREEN}✓${NC} $*"; }
fail() { echo -e "  ${RED}✗${NC} $*" >&2; }
warn() { echo -e "  ${YELLOW}!${NC} $*"; }

HAD_EXISTING_TOML=0
BEFORE_SUM=""

cleanup() {
  # Restore or remove wrangler.toml
  if [[ "$HAD_EXISTING_TOML" == "1" ]] && [[ -f "$BACKUP_TOML" ]]; then
    mv "$BACKUP_TOML" "$TOML_PATH"
  elif [[ -f "$TOML_PATH" ]]; then
    rm -f "$TOML_PATH"
  fi
  # Clean temp files
  rm -rf "$OUT_DIR"
  rm -f "$BACKUP_TOML"
}

trap cleanup EXIT

echo ""
echo "=== Wrangler nanok Bundle Test ==="
echo ""

# ── Check prerequisites ─────────────────────────────────────────────────────

if ! command -v node &>/dev/null; then
  fail "node not found. Install Node.js first."
  exit 1
fi
pass "node: $(node --version)"

WRANGLER=""
if command -v npx &>/dev/null; then
  WRANGLER="npx wrangler"
elif command -v wrangler &>/dev/null; then
  WRANGLER="wrangler"
else
  fail "wrangler not found. Install with: npm install -g wrangler"
  exit 1
fi
pass "wrangler detected"

# ── Backup existing wrangler.toml ───────────────────────────────────────────

echo ""
echo "--- Generating test wrangler.toml ---"
echo ""

if [[ -f "$TOML_PATH" ]]; then
  HAD_EXISTING_TOML=1
  cp "$TOML_PATH" "$BACKUP_TOML"
  BEFORE_SUM=$(cksum "$TOML_PATH" 2>/dev/null | awk '{print $1}' || shasum "$TOML_PATH" 2>/dev/null | awk '{print $1}' || true)
  warn "Existing wrangler.toml backed up, will restore after test"
fi

cat > "$TOML_PATH" <<'EOF'
# Test wrangler.toml — generated by tests/wrangler-nanok-dry-run.sh
name = "nanok-test"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "SUB_STORE"
id = "00000000000000000000000000000000"

[vars]
SUB_PATH = "/jb"
ADMIN_PATH = "/admin/update"
ADMIN_CURRENT_PATH = "/admin/current"
EOF

pass "Generated test wrangler.toml"

# ── Run wrangler deploy --dry-run ───────────────────────────────────────────

echo ""
echo "--- Running wrangler deploy --dry-run ---"
echo ""

rm -rf "$OUT_DIR"

if (
  cd "$WORKER_DIR"
  $WRANGLER deploy --dry-run --outdir "$OUT_DIR" --config wrangler.toml 2>&1
); then
  pass "wrangler deploy --dry-run succeeded"
else
  fail "wrangler deploy --dry-run failed"
  exit 1
fi

# ── Check output ────────────────────────────────────────────────────────────

echo ""
echo "--- Checking bundle output ---"
echo ""

if [[ -d "$OUT_DIR" ]]; then
  local_count=$(find "$OUT_DIR" -type f | wc -l | tr -d ' ')
  pass "Output directory: ${OUT_DIR} (${local_count} files)"

  if [[ -f "$OUT_DIR/index.js" ]]; then
    pass "Bundle output contains index.js"
    local_size=$(wc -c < "$OUT_DIR/index.js" | tr -d ' ')
    pass "Bundle size: ${local_size} bytes"
  else
    if find "$OUT_DIR" -name '*.js' -type f | head -1 | grep -q .; then
      pass "Bundle output contains JS file(s)"
    else
      fail "No JS output found in ${OUT_DIR}"
      exit 1
    fi
  fi
else
  fail "Output directory not found: ${OUT_DIR}"
  exit 1
fi

# ── Done — cleanup trap will restore state ──────────────────────────────────

echo ""
echo -e "  ${GREEN}Bundle test passed!${NC}"

# Verify restore before trap runs
if [[ "$HAD_EXISTING_TOML" == "1" ]]; then
  # Will be restored by trap; verify backup exists
  if [[ -f "$BACKUP_TOML" ]]; then
    pass "Backup file ready for restore"
  fi
else
  # Will be deleted by trap; nothing to verify here
  :
fi
echo ""
