# Hysteria2 Server Configuration
# Generated by NanoBK Proxy Suite installer
# Do NOT commit this file with real credentials.

listen: :__HY2_PORT__

tls:
  cert: __CERT_FILE__
  key: __KEY_FILE__

auth:
  type: password
  password: "__HY2_PASSWORD__"

masquerade:
  type: proxy
  proxy:
    url: https://www.microsoft.com
    rewriteHost: true
