#!/usr/bin/env bash
# NanoBK Proxy Suite — Rollback Example
#
# This is an example rollback script. The actual rollback script is
# auto-generated by rotate-keys.sh in the backup directory.
#
# Usage:
#   bash /root/proxy-key-rotation-backup-YYYYMMDD-HHMMSS/rollback.sh
#
# This file is for reference only.

set -Eeuo pipefail

echo "This is an example rollback script."
echo "The actual rollback script is generated per-rotation in the backup directory."
echo ""
echo "To find your latest backup:"
echo "  ls -lt /root/proxy-key-rotation-backup-*/ | head"
echo ""
echo "To run rollback:"
echo "  bash /root/proxy-key-rotation-backup-YYYYMMDD-HHMMSS/rollback.sh"
echo ""
echo "To restore Cloudflare profile:"
echo '  curl -X POST https://YOUR_WORKER/admin/update \'
echo '    -H "Authorization: Bearer YOUR_ADMIN_TOKEN" \'
echo '    -H "Content-Type: application/json" \'
echo '    --data-binary @/root/proxy-key-rotation-backup-YYYYMMDD-HHMMSS/cf-profile-old.json'
